apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ledger-db
  description: Base de datos PostgreSQL que almacena los asientos contables del core-ledger-service
  tags: [postgresql, database]
spec:
  type: database
  owner: platform-sre-team
  system: payments-platform
