apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: merchant-portal
  description: Portal web donde pymes y comercios gestionan cobros, pagos, financiamiento y su cuenta en FinBridge
  tags: [react, typescript, frontend]
spec:
  type: website
  lifecycle: production
  owner: merchant-experience-team
  system: merchant-experience
  dependsOn:
    - component:api-gateway
