apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-ledger-service
  description: Lleva el registro contable de doble entrada de todas las transacciones (cobros, pagos, desembolsos) de la plataforma
  tags: [java, quarkus, ledger]
spec:
  type: service
  lifecycle: production
  owner: fintech-core-team
  system: payments-platform
  dependsOn:
    - resource:ledger-db
