apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bank-connector-vertice
  description: Conector propietario hacia el Banco Vértice (saldos, transferencias, estados de cuenta) para el bank-aggregator
  tags: [nodejs, connector, open-banking, banco-vertice]
spec:
  type: service
  lifecycle: production
  owner: banking-integrations-team
  system: banking-integration
