apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notifications-service
  description: Envía notificaciones (email, SMS, push) a comercios y pymes sobre el estado de cobros, pagos y su cuenta
  tags: [nodejs, rest, notifications]
spec:
  type: service
  lifecycle: production
  owner: merchant-experience-team
  system: merchant-experience
  dependsOn:
    - resource:message-broker
