apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bank-connector-meridiano
  description: Conector propietario hacia el Banco Meridiano (saldos, transferencias, estados de cuenta) para el bank-aggregator
  tags: [nodejs, connector, open-banking, banco-meridiano]
spec:
  type: service
  lifecycle: production
  owner: banking-integrations-team
  system: banking-integration
