apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cache
  description: Caché en memoria compartida usada por credit-scoring-service y fraud-risk-service para decisiones en tiempo real
  tags: [redis, cache]
spec:
  type: cache
  owner: platform-sre-team
  system: payments-platform
